//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umea.se.ExempelApplikation.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umea.se.ExempelApplikation.Utilities.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anställd fr o m.
        /// </summary>
        public static string AnstalldDatum {
            get {
                return ResourceManager.GetString("AnstalldDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anvandare.
        /// </summary>
        public static string Anvandare {
            get {
                return ResourceManager.GetString("Anvandare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt redigering.
        /// </summary>
        public static string AvbrytRedigering {
            get {
                return ResourceManager.GetString("AvbrytRedigering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurs.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to åååå-mm-dd.
        /// </summary>
        public static string DatumFormat {
            get {
                return ResourceManager.GetString("DatumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string DatumFormatCode {
            get {
                return ResourceManager.GetString("DatumFormatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diskriminator.
        /// </summary>
        public static string Diskriminator {
            get {
                return ResourceManager.GetString("Diskriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efternamn.
        /// </summary>
        public static string Efternamn {
            get {
                return ResourceManager.GetString("Efternamn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel har uppstått.
        /// </summary>
        public static string Ett_fel_har_uppstatt {
            get {
                return ResourceManager.GetString("Ett_fel_har_uppstatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhantering.
        /// </summary>
        public static string Felhantering {
            get {
                return ResourceManager.GetString("Felhantering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förnamn.
        /// </summary>
        public static string Fornamn {
            get {
                return ResourceManager.GetString("Fornamn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledig.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personen är nu ledigmarkerad.
        /// </summary>
        public static string FreeText {
            get {
                return ResourceManager.GetString("FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hjälp.
        /// </summary>
        public static string Hjalp {
            get {
                return ResourceManager.GetString("Hjalp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemort.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruktörsuppgifter.
        /// </summary>
        public static string InstructorUppgifter {
            get {
                return ResourceManager.GetString("InstructorUppgifter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mer....
        /// </summary>
        public static string Mer_dot {
            get {
                return ResourceManager.GetString("Mer_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        public static string Ort {
            get {
                return ResourceManager.GetString("Ort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orter.
        /// </summary>
        public static string Orter {
            get {
                return ResourceManager.GetString("Orter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personuppgifter.
        /// </summary>
        public static string Personuppgifter {
            get {
                return ResourceManager.GetString("Personuppgifter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redigera.
        /// </summary>
        public static string Redigera {
            get {
                return ResourceManager.GetString("Redigera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rensa.
        /// </summary>
        public static string Rensa {
            get {
                return ResourceManager.GetString("Rensa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök.
        /// </summary>
        public static string Sok {
            get {
                return ResourceManager.GetString("Sok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sökningen gav inga träffar.
        /// </summary>
        public static string Sokningen_gav_inga_traffar {
            get {
                return ResourceManager.GetString("Sokningen_gav_inga_traffar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök person.
        /// </summary>
        public static string SokPersoner {
            get {
                return ResourceManager.GetString("SokPersoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        public static string Spara {
            get {
                return ResourceManager.GetString("Spara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stäng.
        /// </summary>
        public static string Stang {
            get {
                return ResourceManager.GetString("Stang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka.
        /// </summary>
        public static string Tillbaka {
            get {
                return ResourceManager.GetString("Tillbaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj....
        /// </summary>
        public static string Valj_dot {
            get {
                return ResourceManager.GetString("Valj_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Var snäll och meddelan supporten..
        /// </summary>
        public static string Var_snall_meddela {
            get {
                return ResourceManager.GetString("Var_snall_meddela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hjälpdokument.
        /// </summary>
        public static string VisaHjalp {
            get {
                return ResourceManager.GetString("VisaHjalp", resourceCulture);
            }
        }
    }
}
