//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umea.se.ExempelApplikation.DataObjectLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Course
    {
        public Course()
        {
            this.Enrollment = new HashSet<Enrollment>();
            this.Person = new HashSet<Person>();
        }
    
        [DataMember]
        public int CourseID { get; set; }
        [DataMember]
        public string Title { get; set; }
        [DataMember]
        public int Credits { get; set; }
        [DataMember]
        public int DepartmentID { get; set; }
    
        [DataMember]
        public virtual Department Department { get; set; }
        [DataMember]
        public virtual ICollection<Enrollment> Enrollment { get; set; }
        [DataMember]
        public virtual ICollection<Person> Person { get; set; }
    }
}
