//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umea.se.ExempelApplikation.DataObjectLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Department
    {
        public Department()
        {
            this.Course = new HashSet<Course>();
        }
    
        [DataMember]
        public int DepartmentID { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public decimal Budget { get; set; }
        [DataMember]
        public System.DateTime StartDate { get; set; }
        [DataMember]
        public Nullable<int> InstructorID { get; set; }
        [DataMember]
        public byte[] RowVersion { get; set; }
    
        [DataMember]
        public virtual ICollection<Course> Course { get; set; }
        [DataMember]
        public virtual Person Person { get; set; }
    }
}
