//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umea.se.ExempelApplikation.DataObjectLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Home
    {
        public Home()
        {
            this.Person = new HashSet<Person>();
        }
    
        [DataMember]
        public int HomeId { get; set; }
        [DataMember]
        public string HomeText { get; set; }
        [DataMember]
        public Nullable<int> CountryId { get; set; }
    
        [DataMember]
        public virtual ICollection<Person> Person { get; set; }
        [DataMember]
        public virtual Country Country { get; set; }
    }
}
