//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umea.se.ExempelApplikation.DataObjectLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Person
    {
        public Person()
        {
            this.Department = new HashSet<Department>();
            this.Enrollment = new HashSet<Enrollment>();
            this.Course = new HashSet<Course>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string LastName { get; set; }
        [DataMember]
        public string FirstName { get; set; }
        [DataMember]
        public Nullable<System.DateTime> HireDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        [DataMember]
        public string Discriminator { get; set; }
        [DataMember]
        public Nullable<int> HomeId { get; set; }
    
        [DataMember]
        public virtual ICollection<Department> Department { get; set; }
        [DataMember]
        public virtual ICollection<Enrollment> Enrollment { get; set; }
        [DataMember]
        public virtual OfficeAssignment OfficeAssignment { get; set; }
        [DataMember]
        public virtual ICollection<Course> Course { get; set; }
        [DataMember]
        public virtual Home Home { get; set; }
    }
}
