//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umea.se.ExempelApplikation.ServiceWrapper.PersonServiceTier {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Umea.se.ExempelApplikation.Utilities.Exce" +
        "ptions")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Umea.se.ExempelApplikation.ServiceWrapper.PersonServiceTier.ErrorCodes CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Umea.se.ExempelApplikation.ServiceWrapper.PersonServiceTier.ErrorCodes Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogId {
            get {
                return this.LogIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LogIdField, value) != true)) {
                    this.LogIdField = value;
                    this.RaisePropertyChanged("LogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCodes", Namespace="http://schemas.datacontract.org/2004/07/Umea.se.ExempelApplikation.Utilities.Exce" +
        "ptions")]
    public enum ErrorCodes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogicValidationException = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecurityException = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SqlException = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonServiceTier.IPersonService")]
    public interface IPersonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPersonerByMany", ReplyAction="http://tempuri.org/IPersonService/GetPersonerByManyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Umea.se.ExempelApplikation.ServiceWrapper.PersonServiceTier.Error), Action="http://tempuri.org/IPersonService/GetPersonerByManyErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Umea.se.ExempelApplikation.Utilities.Exce" +
            "ptions")]
        System.Collections.Generic.List<Umea.se.ExempelApplikation.DataObjectLibrary.Person> GetPersonerByMany(string firstName, string discriminator, System.Collections.Generic.List<Umea.se.ExempelApplikation.DataObjectLibrary.Course> courses);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPersonerByMany", ReplyAction="http://tempuri.org/IPersonService/GetPersonerByManyResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Umea.se.ExempelApplikation.DataObjectLibrary.Person>> GetPersonerByManyAsync(string firstName, string discriminator, System.Collections.Generic.List<Umea.se.ExempelApplikation.DataObjectLibrary.Course> courses);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPersonInformationById", ReplyAction="http://tempuri.org/IPersonService/GetPersonInformationByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Umea.se.ExempelApplikation.ServiceWrapper.PersonServiceTier.Error), Action="http://tempuri.org/IPersonService/GetPersonInformationByIdErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Umea.se.ExempelApplikation.Utilities.Exce" +
            "ptions")]
        Umea.se.ExempelApplikation.DataObjectLibrary.PersonInformation GetPersonInformationById(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPersonInformationById", ReplyAction="http://tempuri.org/IPersonService/GetPersonInformationByIdResponse")]
        System.Threading.Tasks.Task<Umea.se.ExempelApplikation.DataObjectLibrary.PersonInformation> GetPersonInformationByIdAsync(int personId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonServiceChannel : Umea.se.ExempelApplikation.ServiceWrapper.PersonServiceTier.IPersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<Umea.se.ExempelApplikation.ServiceWrapper.PersonServiceTier.IPersonService>, Umea.se.ExempelApplikation.ServiceWrapper.PersonServiceTier.IPersonService {
        
        public PersonServiceClient() {
        }
        
        public PersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Umea.se.ExempelApplikation.DataObjectLibrary.Person> GetPersonerByMany(string firstName, string discriminator, System.Collections.Generic.List<Umea.se.ExempelApplikation.DataObjectLibrary.Course> courses) {
            return base.Channel.GetPersonerByMany(firstName, discriminator, courses);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Umea.se.ExempelApplikation.DataObjectLibrary.Person>> GetPersonerByManyAsync(string firstName, string discriminator, System.Collections.Generic.List<Umea.se.ExempelApplikation.DataObjectLibrary.Course> courses) {
            return base.Channel.GetPersonerByManyAsync(firstName, discriminator, courses);
        }
        
        public Umea.se.ExempelApplikation.DataObjectLibrary.PersonInformation GetPersonInformationById(int personId) {
            return base.Channel.GetPersonInformationById(personId);
        }
        
        public System.Threading.Tasks.Task<Umea.se.ExempelApplikation.DataObjectLibrary.PersonInformation> GetPersonInformationByIdAsync(int personId) {
            return base.Channel.GetPersonInformationByIdAsync(personId);
        }
    }
}
